/*******************************************************************************
 * Copyright (C) 2020 Biza Pty Ltd
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *******************************************************************************/
package io.biza.babelfish.interfaces.cdr.banking.product;

import java.net.URI;
import java.util.List;
import javax.validation.Valid;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import org.inferred.freebuilder.FreeBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.biza.babelfish.converter.cdr.UriStringToUriConverter;
import io.biza.babelfish.converter.cdr.UriToUriStringConverter;
import io.swagger.v3.oas.annotations.media.Schema;

@Valid
@Schema(description = "Banking Product Bundle Definition", name = "BankingProductBundle")
@FreeBuilder
@JsonDeserialize(builder = BankingProductBundleV1.Builder.class)
public interface BankingProductBundleV1 {
  
  /**
   * Fluent Builder Class
   * Generated by FreeBuilder
   *
   */
  class Builder extends BankingProductBundleV1_Builder {}
  
  /**
   * Get the name of the product bundle
   * @return String containing the name of the bundle
   */
  @Schema(description = "Name of the bundle", required = true)
  @NotNull
  @NotBlank
  @Valid
  @JsonProperty("name")
  public String name();

  /**
   * Get the description of the bundle
   * @return a free text description of the bundle
   */
  @Schema(description = "Description of the bundle", required = true)
  @NotNull
  @NotBlank
  @Valid
  @JsonProperty("description")
  public String description();

  /**
   * Get additional information about the bundle
   * @return a free text string with additional bundle information
   */
  @Schema(description = "Display text providing more information on the bundle")
  @JsonProperty("additionalInfo")
  public String additionalInfo();
  
  /**
   * Get additional information address
   * @return a Link to a web page with more information on the bundle criteria and benefits
   */
  @Schema(
      description = "Link to a web page with more information on the bundle criteria and benefits",
      type = "string", format = "uri")
  @JsonSerialize(converter = UriToUriStringConverter.class)
  @JsonDeserialize(converter = UriStringToUriConverter.class)
  @JsonProperty("additionalInfoUri")
  public URI additionalInfoUri();
  
  /**
   * An array of product identifiers included within this bundle. May not contain all products in bundle and specified products may not be available at this endpoint
   * @return a List of String's containing productId's
   */
  @Schema(
      description = "Array of product IDs for products included in the bundle that are available via the product end points.  Note that this array is not intended to represent a comprehensive model of the products included in the bundle and some products available for the bundle may not be available via the product reference end points")
  @JsonProperty("productIds")
  public List<String> productIdentifiers();
  
}
