/*******************************************************************************
 * Copyright (C) 2020 Biza Pty Ltd
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *******************************************************************************/
package io.biza.babelfish.interfaces.cdr.banking.product;

import java.net.URI;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import org.inferred.freebuilder.FreeBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.biza.babelfish.converter.cdr.UriStringToUriConverter;
import io.biza.babelfish.converter.cdr.UriToUriStringConverter;
import io.biza.babelfish.enumerations.cdr.BankingProductDiscountEligibilityType;
import io.swagger.v3.oas.annotations.media.Schema;

@Valid
@Schema(description = "Banking Product Discount Eligibility Details")
@FreeBuilder
@JsonDeserialize(builder = BankingProductFeeDiscountEligibilityV1.Builder.class)
public interface BankingProductFeeDiscountEligibilityV1 {
  
  /**
   * Fluent Builder Class
   * Generated by FreeBuilder
   *
   */
  class Builder extends BankingProductFeeDiscountEligibilityV1_Builder {}
  
  @Schema(description = "The type of the specific eligibility constraint for a discount",
      required = true)
  @NotNull
  @JsonProperty("discountEligibilityType")
  public BankingProductDiscountEligibilityType type();

  @Schema(description = "Additional Value for Eligibility Constraint related to Discount")
  @JsonProperty("additionalValue")
  public String additionalValue();

  @Schema(description = "Display text providing more information on this eligibility constraint")
  @JsonProperty("additionalInfo")
  public String additionalInfo();

  @Schema(description = "Link to a web page with more information on this eligibility constraint",
      type = "string", format = "uri")
  @JsonSerialize(converter = UriToUriStringConverter.class)
  @JsonDeserialize(converter = UriStringToUriConverter.class)
  @JsonProperty("additionalInfoUri")
  public URI additionalInfoUri();

}
