/*******************************************************************************
 * Copyright (C) 2020 Biza Pty Ltd
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *******************************************************************************/
package io.biza.babelfish.interfaces.cdr.banking.product;

import java.math.BigDecimal;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import org.inferred.freebuilder.FreeBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.biza.babelfish.enumerations.cdr.BankingProductRateTierApplicationMethod;
import io.biza.babelfish.enumerations.cdr.CommonUnitOfMeasureType;
import io.swagger.v3.oas.annotations.media.Schema;

@Valid
@Schema(description = "Defines the criteria and conditions for which a rate applies")
@FreeBuilder
@JsonDeserialize(builder = BankingProductRateTierV1.Builder.class)
public interface BankingProductRateTierV1 {
  
  /**
   * Fluent Builder Class
   * Generated by FreeBuilder
   *
   */
  class Builder extends BankingProductRateTierV1_Builder {}
  
  @Schema(description = "A display name for the tier", required = true)
  @NotNull
  @JsonProperty("name")
  public String name();
  
  @Schema(
      description = "The unit of measure that applies to the tierValueMinimum and tierValueMaximum values e.g. 'DOLLAR', 'MONTH' (in the case of term deposit tiers), 'PERCENT' (in the case of loan-to-value ratio or LVR)",
      required = true)
  @NotNull
  @JsonProperty("unitOfMeasure")
  public CommonUnitOfMeasureType unitOfMeasure();

  @Schema(
      description = "The number of tierUnitOfMeasure units that form the lower bound of the tier. The tier should be inclusive of this value",
      required = true)
  @NotNull
  @JsonProperty("minimumValue")
  public BigDecimal minimumValue();

  @Schema(
      description = "The number of tierUnitOfMeasure units that form the upper bound of the tier or band. For a tier with a discrete value (as opposed to a range of values e.g. 1 month) this must be the same as tierValueMinimum. Where this is the same as the tierValueMinimum value of the next-higher tier the referenced tier should be exclusive of this value. For example a term deposit of 2 months falls into the upper tier of the following tiers: (1 – 2 months, 2 – 3 months). If absent the tier's range has no upper bound.")
  @JsonProperty("maximumValue")
  public BigDecimal maximumValue();

  @Schema(
      description = "The method used to calculate the amount to be applied using one or more tiers. A single rate may be applied to the entire balance or each applicable tier rate is applied to the portion of the balance that falls into that tier (referred to as 'bands' or 'steps')")
  @JsonProperty("rateApplicationMethod")
  public BankingProductRateTierApplicationMethod rateApplicationMethod();

  @Schema(description = "Banking Product Rate Applicability Conditions")
  @Valid
  @JsonProperty("applicabilityConditions")
  public BankingProductRateTierApplicabilityV1 applicabilityConditions();

}
