/*******************************************************************************
 * Copyright (C) 2020 Biza Pty Ltd
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *******************************************************************************/
package io.biza.babelfish.interfaces.cdr.banking.product;

import java.util.List;
import javax.validation.Valid;
import org.inferred.freebuilder.FreeBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.v3.oas.annotations.media.Schema;

@Valid
@Schema(description = "Banking Product Detailed Information", allOf = {BankingProductV2.class})
@FreeBuilder
@JsonDeserialize(builder = BankingProductDetailV2.Builder.class)
public interface BankingProductDetailV2 extends BankingProductV2 {
  
  /**
   * Fluent Builder Class
   * Generated by FreeBuilder
   *
   */
  class Builder extends BankingProductDetailV2_Builder {}

  /**
   * Get an array of bundles this product belongs to
   * @return List of Product Bundle information
   */
  @Schema(
      description = "An array of bundles that this product participates in.  Each bundle is described by free form information but also by a list of product IDs of the other products that are included in the bundle.  It is assumed that the current product is included in the bundle also")
  @JsonProperty("bundles")
  @Valid
  public List<BankingProductBundleV1> bundles();

  /**
   * Get an array of product features
   * @return an array of Product Feature objects
   */
  @Schema(description = "Array of features available for the product")
  @JsonProperty("features")
  @Valid
  public List<BankingProductFeatureV1> features();

  /**
   * Get Banking Product Constraints
   * @return a list of constraints for the product
   */
  @Schema(
      description = "Constraints on the application for or operation of the product such as minimum balances or limit thresholds")
  @JsonProperty("constraints")
  @Valid
  public List<BankingProductConstraintV1> constraints();
  
  /**
   * Get Eligibility requirements for a product
   * @return a list of eligibility criteria
   */
  @Schema(description = "Eligibility criteria for the product")
  @JsonProperty("eligibility")
  @Valid
  public List<BankingProductEligibilityV1> eligibility();
  
  /**
   * Get a list of product fees applicable for this product
   * @return List of BankingProductFee for this product
   */
  @Schema(description = "Fees applicable for the product")
  @JsonProperty("fees")
  @Valid
  public List<BankingProductFeeV1> fees();

  @Schema(description = "Interest rates available for deposits")
  @JsonProperty("depositRates")
  @Valid
  public List<BankingProductDepositRateV1> depositRates();

  @Schema(description = "Interest rates charged against lending balances")
  @Valid
  @JsonProperty("lendingRates")
  public List<BankingProductLendingRateV1> lendingRates();
  
}
