sudo: false
language: java
jdk:
  - openjdk11
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "bizaio"
    token:
      secure: "H7IojP0tX8tD3gNK9PpAbjfi44S6czjWrqruxJJQZUHczrnLwtfo2ikskf8FQq2niPraUWxSDTL1pJN8Zvp3R4YSBaozjSnq6zNdnzKfpP3wiXiUu2Ex2Rri9TObqfdVy2RnXvnfmahj3P0KRtVyhiEnCTEPhRfbhgpY8DdB/ZZf7ErzS4W4wCQ3GFoFnL4T+MVPm+FgsvPgFM76wreS9+041DvssW8hL5shrzPRyTCOw5p+rts3tx8CCFuw3US2DUuks5tgiSC7Q7rVOZHHegnQHYrRQFNx4aI4QLHBTBBA5As3VFALq6CG3YK5uopI8Kg+hSe0UMjEcNEs6rpn1LB7DDEzl9om5CYka6mPs+TZdz4A0p/eH6/9eWxuBTtNdZmVtkdkAfcV8Phplo3Cla9GVumtAmGrRp+oJ+wrvz0UxExcXY91dSlG6OhO/xWs2/uVx8erLZDiPOUNpHnY9DW6w3yxR304j8zgZrU7yE/EyoU+z2sbcKK4KJ4zkWrnOsNOmt3Wb1n38puerS981uLViGSXBHJ3OaqFEM41vD7aEhhIZougsN9oZeDqHTe7p5Sol30ORiMezd4nmehI0wSyD1qdnwu6w5rW9y8jzlt6PDcvj8qVcW/9eyoUpZnxDN623XGsfamEitv9V9FwdKhTwcCXqyNip4AAMeThLTQ="

script:
  - mvn clean verify sonar:sonar -Pcoverage 

