/**
 * Babelfish Type Service API
 * This is the Babelfish Type Service API. You can find out more about Babelfish at [https://github.com/bizaio/deepthought](https://github.com/bizaio/babelfish) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.2.6-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BabelFieldType } from './babelFieldType';

/**
 * Type Field Definition
 */
export interface TypeField { 
    /**
     * Type Name
     */
    name: string;
    type: BabelFieldType;
}